import = [
  # uncomment the flavour you want below:
  # ~/.config/alacritty/catppuccin-latte.toml"
  # "~/.config/alacritty/catppuccin-frappe.toml"
   "~/.config/alacritty/catppuccin-macchiato.toml"
  #~/.config/alacritty/catppuccin-mocha.toml"
]

# dynamic_title = true
live_config_reload = true
#"window.opacity" = 1.0

[bell]
animation = "EaseOutExpo"
duration = 0

[colors]
draw_bold_text_with_bright_colors = true

[font]
size = 18.0

[font.bold]
# family = "Fira Code"
# family = "FiraMono Nerd Font"
# family = "FiraCode Nerd Font"
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
# family = "Fira Code"
# family = "FiraMono Nerd Font"
# family = "FiraCode Nerd Font"
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.italic]
# family = "Fira Code"
# family = "FiraMono Nerd Font"
# family = "FiraCode Nerd Font"
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
# family = "Fira Code"
# family = "FiraMono Nerd Font"
# family = "FiraCode Nerd Font"
family = "JetBrainsMono Nerd Font"
style = "Regular"

[window]
# decorations = "transparent"
decorations = "buttonless"
option_as_alt = "Both"

# dynamic_padding = false

[font.glyph_offset]
x = 0
y = 0

[font.offset]
x = 0
y = 0

[mouse]
# faux_scrolling_lines = 1
hide_when_typing = true

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

# [mouse.double_click]
# threshold = 300

# [mouse.triple_click]
# threshold = 300

[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>"

[shell]
program = "/bin/zsh"

[window.dimensions]
columns = 160
lines = 80

[window.padding]
x = 4
y = 4
